---
#
# Ansible managed
#
repository:
  description: Ansible role for install powerlevel10k
  homepage: https://buluma.github.io/
  topics: zsh, shell, system, git, ansible, molecule, tox, playbook, hacktoberfest
