---
# Install powerlevel10k
- name: p10k-install | Ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ p10k_dependencies }}"
    state: present
  become: true
  when: p10k_dependencies

- name: p10k-install | Get ZSH version
  ansible.builtin.shell: "set -o pipefail; zsh --version | cut -d ' ' -f2 | cut -c1-3"
  args:
    executable: /bin/bash
  check_mode: false
  changed_when: false
  register: zsh_version

- name: p10k-install | Powerlevel10k works only with ZSH >= 5.1
  ansible.builtin.fail:
    msg: "You are using ZSH version {{ zsh_version.stdout }}. The minimum required version for Powerlevel10k is 5.1"
  when: zsh_version.stdout|float < 5.1

- name: p10k-install | Install powerlevel10k.
  ansible.builtin.git:
    repo: "{{ p10k_repository_url }}"
    dest: "{{ p10k_path[zsh_plugin] | default('~/powerlevel10k', True) }}"
    depth: '1'
    update: false
    version: 'master'
  become: true
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: p10k-install | Add powerlevel10k to zsh plugin
  ansible.builtin.lineinfile:
    path: "{{ p10k_zshrc_config[zsh_plugin]['zsh_file'] }}"
    regexp: "{{ p10k_zshrc_config[zsh_plugin]['regexp'] }}"
    line: "{{ p10k_zshrc_config[zsh_plugin]['line'] }}"
    mode: '0644'
    create: true
  become: true
  become_user: "{{ item }}"
  with_items: "{{ p10k_users }}"

- name: p10k-install | Enable powerlevel10 instant prompt
  ansible.builtin.blockinfile:
    path: "{{ p10k_zshrc_config[zsh_plugin]['zsh_file'] }}"
    block: |
      if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
      fi
    insertbefore: BOF
    marker_begin: "BEGIN P10K INSTANT PROMPT"
    marker_end: "END P10K INSTANT PROMPT"

- name: p10k-install | Enable powerlevel10k config file
  ansible.builtin.blockinfile:
    path: "{{ p10k_zshrc_config[zsh_plugin]['zsh_file'] }}"
    block: |
      [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    insertafter: EOF
    marker_begin: "BEGIN P10K CONFIG FILE"
    marker_end: "END P10K CONFIG FILE"
