---
- name: Prepare
  hosts: all
  gather_facts: no
  tasks:
    - name: Ubuntu/Debian | refresh apt repository
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_pkg_mgr == "apt"
